.globl _start
_start:

add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
c.add x2,x1
c.add x2,x1


add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
c.add x2,x1
add x0, x0, x0
c.add x2,x1


add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
c.add x2,x1
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
c.add x2,x1


add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
c.add x2,x1
add x0, x0, x0
c.add x2,x1


add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
add x0, x0, x0
ecall