TARGET := tekno_example

C_SRCS := \
	tekno_example.c \

HEADERS := \

CFLAGS := -O3 -fno-builtin-printf -ffunction-sections -nostdlib -Wl,--no-relax

BSP_BASE = ../../

include $(BSP_BASE)/common.mk
