name: Check MD5s and make
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check md5sums
      run: md5sum -c coremark.md5
    - name: make
      run: make
